<?php
$username = $_POST['name'];
$password = $_POST['password'];
$repeatPass = $_POST['repeatPass'];


$conn = new mysqli("localhost", "root", "","WebShopDB") or die("Connect failed: %s\n". $conn -> error);
$lookupName = mysqli_fetch_array(mysqli_query($conn,"SELECT * FROM users WHERE name = '$username'"));


  if($lookupName['name'] == $username){
    echo "Username not available";
  }elseif ($password != $repeatPass) {
    echo "Passwords are not equal";
  }else{
    $hash = password_hash($password, PASSWORD_BCRYPT); // Hashes using bcrypt and autogenerated salt.
    $insertUser = "INSERT INTO users VALUES ('$username', '$hash')";
    mysqli_query($conn, $insertUser);
    echo "Congratulations, $username, you're now ready to shop!";
  }


?>
